name: Torrent 1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999
    steps:
      - name: download ngrok
        shell: powershell
        run: |
          Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip
      - name: run ngrok
        shell: powershell
        run: |
          .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
          Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          
      - name: Activating RDP access.
        run: | 
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        
      - name: Change pass for RDP.
        env: 
          ADMINPASSWORD: ${{ secrets.ADMINPASSWORD }}
        run: |
          net user runneradmin $Env:ADMINPASSWORD >nul
          net localgroup administrators runneradmin /add >nul
          diskperf -Y >nul
          sc config Audiosrv start= auto >nul
          sc start audiosrv >nul
          ICACLS C:\Windows\Temp /grant runneradmin:F >nul
        
      - name: Get Ngrok 
        run: Invoke-WebRequest http://localhost:4040/api/tunnels
        
      - name: download onedrive and tixati
        shell: powershell
        run: |
          Invoke-WebRequest https://download1.tixati.com/download/tixati-3.19-1.win64-install.exe -OutFile tixati.exe
          Start-Process chrome.exe '--new-window https://www.microsoft.com/en-gb/microsoft-365/onedrive/download'
          
      - name: Run loop
        run: ping -t localhost
      - name: Run Loop 2
        shell: powershell
        run: ping -n 10 127.0.0.1
